

#ifndef NAMEDICT_H
#define NAMEDICT_H
#include <cstring>


std::string NAMEDICT[] = {
  "Aaron", "Abigail", "Adam", "Adrian", "Aidan", "Alan", "Albert", "Alex", "Alexander", "Alexandra",
  "Alice", "Alicia", "Allison", "Amanda", "Amber", "Amy", "Andrea", "Andrew", "Angela", "Anna",
  "Anthony", "Ashley", "Austin", "Barbara", "Benjamin", "Beth", "Bethany", "Betty", "Beverly", "Bill",
  "Billy", "Blake", "Bobby", "Bonnie", "Brad", "Bradley", "Brandon", "Brenda", "Brent", "Brett",
  "Brian", "Brittany", "Brooke", "Bruce", "Bryan", "Caitlin", "Caleb", "Calvin", "Cameron", "Carl",
  "Carlos", "Carmen", "Carol", "Caroline", "Casey", "Cassandra", "Catherine", "Cathy", "Chad", "Charles",
  "Charlotte", "Chelsea", "Cheryl", "Chris", "Christian", "Christina", "Christine", "Christopher", "Cindy", "Claire",
  "Clara", "Clarence", "Claude", "Claudia", "Clifford", "Clint", "Clinton", "Cody", "Colin", "Colleen",
  "Connie", "Connor", "Corey", "Courtney", "Craig", "Crystal", "Curtis", "Cynthia", "Dale", "Dan",
  "Dana", "Daniel", "Danielle", "Danny", "Darrell", "Darren", "Dave", "David", "Dawn", "Dean",
  "Debbie", "Deborah", "Debra", "Denise", "Dennis", "Derek", "Derrick", "Diana", "Diane", "Dolores",
  "Don", "Donald", "Donna", "Doris", "Dorothy", "Douglas", "Drew", "Duane", "Dustin", "Dylan",
  "Earl", "Eddie", "Edgar", "Edith", "Edward", "Edwin", "Eileen", "Elaine", "Eleanor", "Elizabeth",
  "Ellen", "Elsa", "Emily", "Emma", "Eric", "Erica", "Erik", "Erin", "Ernest", "Ethan",
  "Eugene", "Eva", "Evan", "Evelyn", "Faith", "Felicia", "Felix", "Florence", "Floyd", "Frances",
  "Francis", "Frank", "Franklin", "Fred", "Frederick", "Gabriel", "Gail", "Garrett", "Gary", "Gavin",
  "Gene", "Geoffrey", "George", "Gerald", "Geraldine", "Gilbert", "Gina", "Glen", "Glenn", "Gloria",
  "Gordon", "Grace", "Grant", "Greg", "Gregory", "Gretchen", "Gwen", "Hailey", "Haley", "Hannah",
  "Harold", "Harry", "Harvey", "Hayden", "Hayley", "Heather", "Helen", "Henry", "Herbert", "Holly",
  "Howard", "Hunter", "Ian", "Ida", "Isaac", "Isabel", "Isabella", "Jack", "Jackie", "Jacob",
  "Jacqueline", "Jade", "Jake", "James", "Jamie", "Jane", "Janet", "Janice", "Jared", "Jason",
  "Jay", "Jean", "Jeff", "Jeffrey", "Jennifer", "Jenny", "Jeremy", "Jerome", "Jerry", "Jesse",
  "Jessica", "Jill", "Jim", "Jimmy", "Jo", "Joan", "Joanne", "Joe", "Joel", "John",
  "Johnny", "Jonathan", "Jordan", "Joseph", "Josephine", "Joshua", "Joyce", "Judith", "Judy", "Julia",
  "Julian", "Julie", "June", "Justin", "Karen", "Kate", "Katherine", "Kathleen", "Kathryn", "Kathy",
  "Katie", "Kay", "Keith", "Kelly", "Ken", "Kenneth", "Kenny", "Kevin", "Kim", "Kimberly",
  "Kirk", "Kristen", "Kristin", "Kristina", "Kristy", "Kurt", "Kyle", "Lance", "Larry", "Laura",
  "Lauren", "Laurie", "Lawrence", "Leah", "Lee", "Lena", "Leo", "Leonard", "Leroy", "Leslie",
  "Lester", "Lewis", "Lillian", "Lily", "Linda", "Lindsay", "Lindsey", "Lisa", "Lloyd", "Logan",
  "Lois", "Lori", "Lorraine", "Louis", "Louise", "Lucas", "Lucy", "Luke", "Lydia", "Lynn",
  "Mabel", "Madison", "Maggie", "Malcolm", "Mandy", "Manuel", "Marc", "Marcia", "Marcus", "Margaret",
  "Maria", "Mariah", "Marie", "Marilyn", "Marion", "Marjorie", "Mark", "Marlene", "Marsha", "Martha",
  "Martin", "Marvin", "Mary", "Mason", "Mathew", "Matthew", "Maureen", "Maurice", "Max", "Megan",
  "Melanie", "Melissa", "Melvin", "Michael", "Michelle", "Mickey", "Miguel", "Mike", "Mildred", "Miranda",
  "Mitchell", "Molly", "Monica", "Morgan", "Nancy", "Natalie", "Nathan", "Neil", "Nicholas", "Nicole",
  "Nina", "Noah", "Nora", "Norma", "Norman", "Olivia", "Omar", "Oscar", "Paige", "Pamela",
  "Patricia", "Patrick", "Paul", "Paula", "Pauline", "Pearl", "Peggy", "Penny", "Perry", "Peter",
  "Philip", "Phillip", "Phyllis", "Preston", "Priscilla", "Rachel", "Ralph", "Randall", "Randy", "Ray",
  "Raymond", "Rebecca", "Regina", "Renee", "Rhonda", "Richard", "Rick", "Ricky", "Rita", "Robert",
  "Roberta", "Roberto", "Robin", "Rodney", "Roger", "Roland", "Ron", "Ronald", "Ronnie", "Rosa",
  "Rose", "Rosemary", "Ross", "Roy", "Ruby", "Russell", "Ruth", "Ryan", "Sabrina", "Sally",
  "Sam", "Samantha", "Samuel", "Sandra", "Sara", "Sarah", "Scott", "Sean", "Shane", "Shannon",
  "Sharon", "Shawn", "Sheila", "Shelby", "Shelly", "Sherri", "Sherry", "Shirley", "Sierra", "Simon",
  "Sonia", "Sophia", "Spencer", "Stacey", "Stacy", "Stanley", "Stephanie", "Stephen", "Steve", "Steven",
  "Sue", "Susan", "Suzanne", "Sydney", "Sylvia", "Tabitha", "Tamara", "Tammy", "Tanner", "Tara",
  "Taylor", "Ted", "Teresa", "Terrance", "Terri", "Terry", "Thelma", "Theodore", "Theresa", "Thomas",
  "Tiffany", "Tim", "Timothy", "Tina", "Todd", "Tom", "Tommy", "Toni", "Tony", "Tracy",
  "Travis", "Trevor", "Tricia", "Troy", "Tyler", "Tyrone", "Valerie", "Vanessa", "Vera", "Verna",
  "Vernon", "Veronica", "Victor", "Victoria", "Vincent", "Viola", "Violet", "Virginia", "Vivian", "Wade",
  "Wallace", "Walter", "Wanda", "Warren", "Wayne", "Wendy", "Wesley", "Whitney", "Wilbur", "Willard",
  "William", "Willie", "Wilma", "Winifred", "Wyatt", "Xavier", "Yvonne", "Zachary", "Zoe",
  
  "Aaliyah", "Abdul", "Aiko", "Akira", "Alessandro", "Alexei", "Ali", "Amir", "Ananya", "Anastasia",
  "Andres", "Angelica", "Anita", "Anya", "Arjun", "Asuka", "Ava", "Axel", "Ayaan", "Ayana",
  "Baptiste", "Beatriz", "Bianca", "Bjorn", "Bruno", "Camila", "Carla", "Carlo", "Catalina", "Celeste",
  "Cesare", "Chan", "Cheng", "Chiara", "Chika", "Chow", "Chu", "Damien", "Daria", "Dario",
  "Deepak", "Dimitri", "Divya", "Dominique", "Elena", "Elias", "Emiliano", "Emilio", "Emir", "Enrique",
  "Esperanza", "Esteban", "Esther", "Etsuko", "Fabio", "Fareed", "Fatima", "Fiona", "Francesco", "Franco",
  "Franz", "Fumiko", "Gabriela", "Gabrielle", "Genevieve", "Gianna", "Giselle", "Giuseppe", "Gunnar", "Gustavo",
  "Hans", "Haruki", "Hassan", "Heidi", "Heinrich", "Helena", "Henri", "Hikaru", "Hiroshi", "Hugo",
  "Ibrahim", "Ines", "Ingrid", "Ioana", "Irene", "Iris", "Irma", "Isabella", "Isadora", "Ismail",
  "Ivan", "Ivana", "Jae", "Jakub", "Jalil", "Jan", "Jana", "Javier", "Jean-Baptiste", "Ji-Young",
  "Jian", "Jin", "João", "Joaquin", "Johann", "Jonas", "Jorge", "Josef", "Juan", "Juliana",
  "Julio", "Jun", "Jürgen", "Kai", "Kaito", "Kamil", "Karina", "Karla", "Karolina", "Katarina",
  "Katja", "Keiko", "Kenji", "Klaus", "Kobayashi", "Kofi", "Kristof", "Lara", "Lars", "Layla",
  "Lea", "Lena", "Leon", "Leonie", "Li", "Ling", "Linus", "Lola", "Lorenzo", "Luca",
  "Lucia", "Luciana", "Luigi", "Luis", "Luisa", "Luka", "Lukas", "Maia", "Maiko", "Malek",
  "Manuela", "Marcello", "Marco", "Margarita", "Margot", "Mari", "Maria", "Mariana", "Marianne", "Mario",
  "Marko", "Markus", "Marlene", "Marta", "Martina", "Masaru", "Mateo", "Mathias", "Matias", "Matteo",
  "Matthias", "Maxim", "Maxime", "Mei", "Mei-Ling", "Mia", "Micaela", "Mikael", "Miki", "Milan",
  "Minh", "Miriam", "Miyuki", "Mohamed", "Mohammad", "Mohammed", "Monique", "Nadia", "Nadine", "Naomi",
  "Natasha", "Naveen", "Nicola", "Nicolai", "Nicolás", "Niels", "Nikita", "Nikolai", "Nils", "Nina",
  "Nora", "Nuria", "Olaf", "Olga", "Oliver", "Olivia", "Omar", "Osamu", "Pablo", "Paolo",
  "Pascal", "Patrice", "Pavel", "Pedro", "Petra", "Pierre", "Piotr", "Priya", "Rafa", "Rafael",
  "Rajan", "Rajesh", "Ramón", "Raúl", "Ravi", "Reiko", "Renata", "Ricardo", "Rishi", "Roberto",
  "Rodrigo", "Rolf", "Roman", "Rory", "Rosa", "Rosalba", "Rosario", "Roxana", "Ruben", "Sabine",
  "Said", "Salim", "Salvatore", "Sami", "Samira", "Sanjay", "Santiago", "Sara", "Satoshi", "Selena",
  "Selma", "Seong", "Sergei", "Sergio", "Shigeru", "Shiro", "Silvana", "Silvia", "Simone", "Sofía",
  "Sonja", "Sophie", "Stefan", "Stefano", "Stephanie", "Sung", "Sven", "Svetlana", "Takashi", "Takeshi",
  "Tariq", "Tatiana", "Thiago", "Thomas", "Tomas", "Tomoko", "Ulrich", "Ursula", "Valentina", "Valeria",
  "Viktor", "Vincent", "Vittorio", "Vladimir", "Wei", "Wolfgang", "Xiang", "Xiuying", "Yael", "Yan",
  "Yannis", "Yasmin", "Yoko", "Yolanda", "Yong", "Yoshiko", "Yuki", "Yuri", "Yusef", "Yvette",
  "Zara", "Zeynep", "Zhang", "Zhen", "Zhi", "Zofia",
  
  "Addison", "Aerith", "Ainsley", "Amari", "Aria", "Ariana", "Arya", "Ashton", "Aspen", "Atlas",
  "Atticus", "Aurora", "Avery", "Beckett", "Bellamy", "Bodhi", "Briar", "Brooklyn", "Cairo", "Camden",
  "Carter", "Cassian", "Chloe", "Cora", "Cyrus", "Dakota", "Daleyza", "Declan", "Eden", "Eliana",
  "Elijah", "Elliot", "Eloise", "Emerson", "Emery", "Emmett", "Everett", "Everleigh", "Everly", "Ezra",
  "Finley", "Flynn", "Freya", "Grayson", "Griffin", "Harper", "Harlow", "Haven", "Hayes", "Hazel",
  "Hudson", "Imogen", "Indigo", "Isla", "Ivy", "Jace", "Jaden", "Jaiden", "Jasper", "Jayden",
  "Juniper", "Kai", "Kailani", "Kaiser", "Kalani", "Kennedy", "Kinsley", "Knox", "Kylo", "Lachlan",
  "Landon", "Lennon", "Lennox", "Leo", "Lincoln", "Linden", "Luna", "Maddox", "Maeve", "Maverick",
  "Milo", "Nash", "Nico", "Nova", "Oakley", "Ocean", "Orion", "Parker", "Penelope", "Phoenix",
  "Piper", "Quinn", "Remi", "Remington", "Rhys", "Riley", "River", "Ronan", "Rory", "Rowan",
  "Ryder", "Ryker", "Sage", "Sawyer", "Scarlett", "Scout", "Serenity", "Sienna", "Skye", "Sloane",
  "Soren", "Sterling", "Sullivan", "Sutton", "Tatum", "Tegan", "Thea", "Theo", "Theodore", "Thorne",
  "Trinity", "Tristan", "Violet", "Weston", "Wilder", "Willa", "Willow", "Winter", "Wren", "Xander",
  "Zane", "Zephyr", "Zion"};

int totalNames = sizeof(NAMEDICT) / sizeof(NAMEDICT[0]);
#endif /* NAMEDICT_H */

